#!/usr/bin/env ruby
# Copyright (C) 2014 Continuent, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.  You may obtain
# a copy of the License at
# 
#         http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Initial developer(s): Jeff Mace
# Contributor(s):

begin
  require 'rubygems'
  gem 'continuent-tools-core'
rescue LoadError
end

require 'continuent-tools-core'

# This script will look for an active instance of Continuent Tungsten
# If $CONTINUENT_ROOT is not set, the path must be passed in with
# --directory
class ActiveTungstenScript
  include TungstenScript
  
  def main
    TU.notice("I am running against #{TI.root()}")
  end
  
  def configure
    super()
  end
  
  def validate
    super()
    
    unless TU.is_valid?()
      return TU.is_valid?()
    end
  end
  
  def script_name
    "active-directory-script"
  end
end

ActiveTungstenScript.new().run()